-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 06:53:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rsdea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rsdea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rsdea` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sik
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sik` DEFAULT CHARACTER SET latin1 ;
USE `rsdea` ;

-- -----------------------------------------------------
-- Table `rsdea`.`pasien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`pasien` (
  `no_rm` VARCHAR(23) NOT NULL,
  `no_kk` VARCHAR(45) NOT NULL,
  `no_ktp` VARCHAR(24) NOT NULL,
  `nama` VARCHAR(45) NULL,
  `kelamin` ENUM("laki", "perempuan") NULL,
  `tmpt_lhr` VARCHAR(45) NULL,
  `tgl_lhr` DATE NULL,
  `gol_drh` ENUM("A", "B", "AB", "O") NULL,
  `pekerjaan` VARCHAR(45) NULL,
  `status` ENUM("single", "Janda", "Duda") NULL,
  `Agama` ENUM("islam", "kristen", "katholk", "hindu", "budha", "konghucu", "kepercayaan lain") NULL,
  `tgl_dftr` DATETIME NULL,
  `no_tlp` VARCHAR(45) NULL,
  `usia` VARCHAR(45) NULL,
  `alamat` VARCHAR(45) NULL,
  `negara` VARCHAR(45) NULL,
  `kota` VARCHAR(45) NULL,
  `kecamatan` VARCHAR(45) NULL,
  `kelurahan` VARCHAR(45) NULL,
  `rt` VARCHAR(45) NULL,
  `rw` VARCHAR(45) NULL,
  `pendidikan` ENUM("SD", "SMP", "SMA", "S1", "S2", "S3") NULL,
  `wali` VARCHAR(45) NULL,
  `sidik_jari` INT NOT NULL,
  `kd_fisik` INT NOT NULL,
  PRIMARY KEY (`no_rm`),
  INDEX `fk_pasien_sidik_jari1_idx` (`sidik_jari` ASC) VISIBLE,
  INDEX `fk_pasien_fisik_pasen1_idx` (`kd_fisik` ASC) VISIBLE,
  CONSTRAINT `fk_pasien_sidik_jari1`
    FOREIGN KEY (`sidik_jari`)
    REFERENCES `rsdea`.`sidik_jari` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasien_fisik_pasen1`
    FOREIGN KEY (`kd_fisik`)
    REFERENCES `rsdea`.`fisik_pasen` (`kd_fisik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`dokter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`dokter` (
  `kd_dr` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `spesialis` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_dr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`petugas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`petugas` (
  `id_petugas` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `jk` ENUM("laki", "perempuan") NULL,
  `tmp_lahir` VARCHAR(45) NULL,
  `tgl_lahir` DATE NULL,
  `alamat` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id_petugas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`reg_periksa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`reg_periksa` (
  `no_rawat` INT NOT NULL,
  `tgl_registrasi` DATE NULL,
  `jam_registrasi` TIME NULL,
  `no_rm` VARCHAR(23) NOT NULL,
  `kd_dokter` INT NOT NULL,
  `id_petugas` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`no_rawat`),
  INDEX `fk_reg_periksa_pasien_idx` (`no_rm` ASC) VISIBLE,
  INDEX `fk_reg_periksa_dokter1_idx` (`kd_dokter` ASC) VISIBLE,
  INDEX `fk_reg_periksa_petugas2_idx` (`id_petugas` ASC) VISIBLE,
  CONSTRAINT `fk_reg_periksa_pasien`
    FOREIGN KEY (`no_rm`)
    REFERENCES `rsdea`.`pasien` (`no_rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_periksa_dokter1`
    FOREIGN KEY (`kd_dokter`)
    REFERENCES `rsdea`.`dokter` (`kd_dokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_periksa_petugas2`
    FOREIGN KEY (`id_petugas`)
    REFERENCES `rsdea`.`petugas` (`id_petugas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`obat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`obat` (
  `kode_obat` INT NOT NULL,
  `nama_obat` VARCHAR(45) NULL,
  `harga` INT NULL,
  PRIMARY KEY (`kode_obat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`pemberian_obat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`pemberian_obat` (
  `no_rawat` INT NOT NULL,
  `kode_obat` INT NOT NULL,
  `diagnosa` VARCHAR(45) NULL,
  `biaya_obat` INT NULL,
  `jml` INT NULL,
  `tambahan` INT NULL,
  `total` INT NULL,
  INDEX `fk_pemberian_obat_reg_periksa1_idx` (`no_rawat` ASC) VISIBLE,
  INDEX `fk_pemberian_obat_obat1_idx` (`kode_obat` ASC) VISIBLE,
  CONSTRAINT `fk_pemberian_obat_reg_periksa1`
    FOREIGN KEY (`no_rawat`)
    REFERENCES `rsdea`.`reg_periksa` (`no_rawat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pemberian_obat_obat1`
    FOREIGN KEY (`kode_obat`)
    REFERENCES `rsdea`.`obat` (`kode_obat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`tarif_tindakan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`tarif_tindakan` (
  `kd_tndakan` INT NOT NULL,
  `kelas` VARCHAR(3) NOT NULL,
  `nm_tindakn` VARCHAR(45) NULL,
  `jenis_bayar` VARCHAR(45) NULL,
  `jasa_sarana` VARCHAR(45) NULL,
  `jasa_pelayananan` VARCHAR(45) NULL,
  `jasa_medik` VARCHAR(45) NULL,
  `bpp` VARCHAR(45) NULL,
  `tarif` FLOAT NULL,
  PRIMARY KEY (`kd_tndakan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`rawat_jalan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`rawat_jalan` (
  `no_rm` INT NOT NULL,
  `diagnosa` VARCHAR(45) NULL,
  `kode_tindakan` INT NOT NULL,
  `suhu_tubuh` INT NULL,
  `tensi` INT NULL,
  `keterangan` VARCHAR(145) NULL,
  `biaya_rawat` INT NULL,
  `kd_dokter` INT NOT NULL,
  INDEX `fk_rawat_jalan_dokter1_idx` (`kd_dokter` ASC) VISIBLE,
  INDEX `fk_rawat_jalan_tarif_tindakan1_idx` (`kode_tindakan` ASC) VISIBLE,
  INDEX `fk_rawat_jalan_pasien1_idx` (`no_rm` ASC) VISIBLE,
  CONSTRAINT `fk_rawat_jalan_dokter1`
    FOREIGN KEY (`kd_dokter`)
    REFERENCES `rsdea`.`dokter` (`kd_dokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rawat_jalan_tarif_tindakan1`
    FOREIGN KEY (`kode_tindakan`)
    REFERENCES `rsdea`.`tarif_tindakan` (`kode_tindakan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rawat_jalan_pasien1`
    FOREIGN KEY (`no_rm`)
    REFERENCES `rsdea`.`pasien` (`no_rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`faskes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`faskes` (
  `kd_faskes` INT NOT NULL,
  `nm_faskes` VARCHAR(45) NULL,
  `alamat` TEXT NULL,
  `kd_pos` VARCHAR(45) NULL,
  `jenis_faskes` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_faskes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`provider` (
  `jenis` INT NOT NULL,
  `nm_provider` VARCHAR(45) NULL,
  `kd_provider` VARCHAR(45) NULL,
  `nm_cbng` VARCHAR(45) NULL,
  `kd_cbng` VARCHAR(45) NULL,
  PRIMARY KEY (`jenis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`vclaim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`vclaim` (
  `versi` ENUM("1", "2") NOT NULL,
  `cons_id` INT NOT NULL,
  `secret_key` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`cons_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`poli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`poli` (
  `kd_poli` INT NOT NULL,
  `nm_poli` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_poli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`perusahaan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`perusahaan` (
  `kategori` VARCHAR(22) NOT NULL,
  `kd_perusahaan` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `alamat` TEXT NULL,
  `kota` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  `kd_rekutang` VARCHAR(45) NULL,
  `kd_rekpiutang` VARCHAR(45) NULL,
  `no_kontrak` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_perusahaan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`kondisi_pasien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`kondisi_pasien` (
  `kd_kondisi` INT NOT NULL,
  `nm_kondisi` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_kondisi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`icd10`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`icd10` (
  `kd_icd` INT NOT NULL,
  `parent` VARCHAR(45) NULL,
  `nm_icd` VARCHAR(45) NULL,
  `alias` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL,
  `ket` TEXT NULL,
  PRIMARY KEY (`kd_icd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`icd9`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`icd9` (
  `kd_icd` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL,
  `alias` VARCHAR(45) NULL,
  `ket` TEXT NULL,
  PRIMARY KEY (`kd_icd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`unit dan tarif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`unit dan tarif` (
  `kd_unit` INT NOT NULL,
  `parent` VARCHAR(45) NULL,
  `nm_unit` VARCHAR(45) NULL,
  `kategori` VARCHAR(45) NULL,
  `pembayaran` VARCHAR(45) NULL,
  `kelas` VARCHAR(45) NULL,
  `tarif` VARCHAR(45) NULL,
  `tarif_konsul` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_unit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`status_pasien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`status_pasien` (
  `kd_status` INT NOT NULL,
  `nama_status` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`penunjang_tarif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`penunjang_tarif` (
  `kd_penunjang` INT NOT NULL,
  `jenis` VARCHAR(45) NULL,
  `kategori` VARCHAR(45) NULL,
  `nm_pemeriksaan` VARCHAR(45) NULL,
  `ket` TEXT NULL,
  PRIMARY KEY (`kd_penunjang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`sarana_kesehatan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`sarana_kesehatan` (
  `jenis_rujukan` VARCHAR(22) NOT NULL,
  `kd_rujukan` VARCHAR(45) NULL,
  `nama` VARCHAR(45) NULL,
  `sarana_kesehatancol` VARCHAR(45) NULL,
  PRIMARY KEY (`jenis_rujukan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`tarif_tindakan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`tarif_tindakan` (
  `kd_tndakan` INT NOT NULL,
  `kelas` VARCHAR(3) NOT NULL,
  `nm_tindakn` VARCHAR(45) NULL,
  `jenis_bayar` VARCHAR(45) NULL,
  `jasa_sarana` VARCHAR(45) NULL,
  `jasa_pelayananan` VARCHAR(45) NULL,
  `jasa_medik` VARCHAR(45) NULL,
  `bpp` VARCHAR(45) NULL,
  `tarif` FLOAT NULL,
  PRIMARY KEY (`kd_tndakan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`jenis_bayar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`jenis_bayar` (
  `kd_bayar` INT NOT NULL,
  `nm_bayar` VARCHAR(45) NULL,
  `standar_kls` VARCHAR(45) NULL,
  `ket` TEXT NULL,
  PRIMARY KEY (`kd_bayar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`kelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`kelas` (
  `kd_kls` INT NOT NULL,
  `nm_kls` VARCHAR(45) NULL,
  `ket` TEXT NULL,
  PRIMARY KEY (`kd_kls`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`ruang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`ruang` (
  `kd_ruang` INT NOT NULL,
  `nm_ruang` VARCHAR(45) NULL,
  `ket` TEXT NULL,
  `kpl_ruang` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_ruang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`pegawai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`pegawai` (
  `no_pgw` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `jk` ENUM("laki", "perempuan") NULL,
  `tmpt_lhr` TEXT NULL,
  `tgl_lhr` DATE NULL,
  `alamat` TEXT NULL,
  `kota` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL,
  `jns_pgw` VARCHAR(45) NULL,
  `fungsional` VARCHAR(45) NULL,
  `jabatan` VARCHAR(45) NULL,
  `pgw_medis` VARCHAR(45) NULL,
  `pendidikan` VARCHAR(45) NULL,
  `tgl_masuk` VARCHAR(45) NULL,
  `aktif` ENUM("Y", "T") NULL,
  PRIMARY KEY (`no_pgw`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`shift` (
  `no_pgw` INT NOT NULL,
  `shif_awal` TIME NULL,
  `shif_akhir` TIME NULL,
  `shif_round` TIME NULL,
  `ket` TEXT NULL,
  INDEX `fk_shift_pegawai1_idx` (`no_pgw` ASC) VISIBLE,
  CONSTRAINT `fk_shift_pegawai1`
    FOREIGN KEY (`no_pgw`)
    REFERENCES `rsdea`.`pegawai` (`no_pgw`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`tarif_pelayanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`tarif_pelayanan` (
  `kelas` VARCHAR(22) NOT NULL,
  `jns_bayar` VARCHAR(45) NULL,
  `jasa_sarana` VARCHAR(45) NULL,
  `jasa_plyn` VARCHAR(45) NULL,
  `jasa_medis` VARCHAR(45) NULL,
  `bhp` VARCHAR(45) NULL,
  `tarif` FLOAT NULL,
  PRIMARY KEY (`kelas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`akun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`akun` (
  `username` VARCHAR(22) NOT NULL,
  `password` VARCHAR(45) NULL,
  `nm_ptgs` VARCHAR(45) NULL,
  `grup` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL,
  `login_awal` TIMESTAMP(22) NULL,
  `login_ahir` TIMESTAMP(22) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`sidik_jari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`sidik_jari` (
  `nama` VARCHAR(33) NOT NULL,
  `sn` INT NOT NULL,
  `vc` VARCHAR(45) NULL,
  `ac` VARCHAR(45) NULL,
  `vkey` VARCHAR(45) NULL,
  `ket` TEXT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`sn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`fisik_pasen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`fisik_pasen` (
  `kd_fisik` INT NOT NULL,
  `tinggi` FLOAT NOT NULL,
  `berat` FLOAT NOT NULL,
  `detak_jtg` FLOAT NOT NULL,
  `tek_darah` DOUBLE NOT NULL,
  `suhu` DOUBLE NULL,
  `napas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kd_fisik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`pasien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`pasien` (
  `no_rm` VARCHAR(23) NOT NULL,
  `no_kk` VARCHAR(45) NOT NULL,
  `no_ktp` VARCHAR(24) NOT NULL,
  `nama` VARCHAR(45) NULL,
  `kelamin` ENUM("laki", "perempuan") NULL,
  `tmpt_lhr` VARCHAR(45) NULL,
  `tgl_lhr` DATE NULL,
  `gol_drh` ENUM("A", "B", "AB", "O") NULL,
  `pekerjaan` VARCHAR(45) NULL,
  `status` ENUM("single", "Janda", "Duda") NULL,
  `Agama` ENUM("islam", "kristen", "katholk", "hindu", "budha", "konghucu", "kepercayaan lain") NULL,
  `tgl_dftr` DATETIME NULL,
  `no_tlp` VARCHAR(45) NULL,
  `usia` VARCHAR(45) NULL,
  `alamat` VARCHAR(45) NULL,
  `negara` VARCHAR(45) NULL,
  `kota` VARCHAR(45) NULL,
  `kecamatan` VARCHAR(45) NULL,
  `kelurahan` VARCHAR(45) NULL,
  `rt` VARCHAR(45) NULL,
  `rw` VARCHAR(45) NULL,
  `pendidikan` ENUM("SD", "SMP", "SMA", "S1", "S2", "S3") NULL,
  `wali` VARCHAR(45) NULL,
  `sidik_jari` INT NOT NULL,
  `kd_fisik` INT NOT NULL,
  PRIMARY KEY (`no_rm`),
  INDEX `fk_pasien_sidik_jari1_idx` (`sidik_jari` ASC) VISIBLE,
  INDEX `fk_pasien_fisik_pasen1_idx` (`kd_fisik` ASC) VISIBLE,
  CONSTRAINT `fk_pasien_sidik_jari1`
    FOREIGN KEY (`sidik_jari`)
    REFERENCES `rsdea`.`sidik_jari` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasien_fisik_pasen1`
    FOREIGN KEY (`kd_fisik`)
    REFERENCES `rsdea`.`fisik_pasen` (`kd_fisik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`daftar_rj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`daftar_rj` (
  `no_rm` VARCHAR(23) NOT NULL,
  `tgl` DATE NULL,
  `jam` TIME NULL,
  `jenis_bayar` ENUM("UMUM", "BPJS") NULL,
  `no_asuransi` INT NULL,
  `penanggung` VARCHAR(45) NULL,
  `kadaluarsa` VARCHAR(45) NULL,
  `kelas` VARCHAR(45) NULL,
  `kd_poli` INT NOT NULL,
  `dokter` VARCHAR(45) NULL,
  `tarif` VARCHAR(45) NULL,
  INDEX `fk_rawat_jalan_pasien2_idx` (`no_rm` ASC) VISIBLE,
  INDEX `fk_daftar_rj_poli1_idx` (`kd_poli` ASC) VISIBLE,
  CONSTRAINT `fk_rawat_jalan_pasien2`
    FOREIGN KEY (`no_rm`)
    REFERENCES `rsdea`.`pasien` (`no_rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_daftar_rj_poli1`
    FOREIGN KEY (`kd_poli`)
    REFERENCES `rsdea`.`poli` (`kd_poli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`dokter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`dokter` (
  `kd_dr` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `spesialis` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_dr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`pelayanan_rj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`pelayanan_rj` (
  `konsul` ENUM("Y", "T") NOT NULL,
  `pelayanan_rjcol` VARCHAR(45) NULL,
  `pasien_no_rm` VARCHAR(23) NOT NULL,
  `dokter_kd_dr` INT NOT NULL,
  `tarif_tindakan_kelas` VARCHAR(3) NOT NULL,
  INDEX `fk_pelayanan_rj_pasien1_idx` (`pasien_no_rm` ASC) VISIBLE,
  INDEX `fk_pelayanan_rj_dokter1_idx` (`dokter_kd_dr` ASC) VISIBLE,
  INDEX `fk_pelayanan_rj_tarif_tindakan1_idx` (`tarif_tindakan_kelas` ASC) VISIBLE,
  CONSTRAINT `fk_pelayanan_rj_pasien1`
    FOREIGN KEY (`pasien_no_rm`)
    REFERENCES `rsdea`.`pasien` (`no_rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelayanan_rj_dokter1`
    FOREIGN KEY (`dokter_kd_dr`)
    REFERENCES `rsdea`.`dokter` (`kd_dr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelayanan_rj_tarif_tindakan1`
    FOREIGN KEY (`tarif_tindakan_kelas`)
    REFERENCES `rsdea`.`tarif_tindakan` (`kelas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`periksa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`periksa` (
  `kd_priksa` INT NOT NULL,
  `standar` VARCHAR(45) NULL,
  `hasil` VARCHAR(45) NULL,
  `satuan` VARCHAR(45) NULL,
  `kd_dr` INT NOT NULL,
  `ket` TEXT NULL,
  `tgl` DATE NULL,
  `waktu` TIME NULL,
  INDEX `fk_periksa_pemeriksaan1_idx` (`kd_priksa` ASC) VISIBLE,
  CONSTRAINT `fk_periksa_pemeriksaan1`
    FOREIGN KEY (`kd_priksa`)
    REFERENCES `rsdea`.`periksa` (`kd_priksa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periksa_dokter1`
    FOREIGN KEY (`kd_dr`)
    REFERENCES `rsdea`.`dokter` (`kd_dr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`periksa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`periksa` (
  `kd_priksa` INT NOT NULL,
  `standar` VARCHAR(45) NULL,
  `hasil` VARCHAR(45) NULL,
  `satuan` VARCHAR(45) NULL,
  `kd_dr` INT NOT NULL,
  `ket` TEXT NULL,
  `tgl` DATE NULL,
  `waktu` TIME NULL,
  INDEX `fk_periksa_pemeriksaan1_idx` (`kd_priksa` ASC) VISIBLE,
  CONSTRAINT `fk_periksa_pemeriksaan1`
    FOREIGN KEY (`kd_priksa`)
    REFERENCES `rsdea`.`periksa` (`kd_priksa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periksa_dokter1`
    FOREIGN KEY (`kd_dr`)
    REFERENCES `rsdea`.`dokter` (`kd_dr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`diagnosa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`diagnosa` (
  `kd_icdX` INT NOT NULL,
  `nm_diagnosa` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_icdX`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`prosedur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`prosedur` (
  `kd_icd` INT NOT NULL,
  `ket` TEXT NULL,
  `tgl` DATE NULL,
  `waktu` TIME NULL,
  INDEX `fk_prosedur_icd91_idx` (`kd_icd` ASC) VISIBLE,
  CONSTRAINT `fk_prosedur_icd91`
    FOREIGN KEY (`kd_icd`)
    REFERENCES `rsdea`.`icd9` (`kd_icd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`tindakan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`tindakan` (
  `kd_tindakan` INT NOT NULL,
  `nm_tindakan` VARCHAR(45) NULL,
  `biaya` DOUBLE NULL,
  PRIMARY KEY (`kd_tindakan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`bhp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`bhp` (
  `kd_barang` INT NOT NULL,
  `nm_barang` VARCHAR(45) NULL,
  `satuan` INT NULL,
  `harga` DOUBLE NULL,
  PRIMARY KEY (`kd_barang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`resep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`resep` (
  `barang` INT NOT NULL,
  `satuan` INT NULL,
  `jumlah` INT NULL,
  `resepcol` VARCHAR(45) NULL,
  PRIMARY KEY (`barang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`kasir_rj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`kasir_rj` (
  `idkasir_rj` INT NOT NULL,
  `no_rm` VARCHAR(23) NOT NULL,
  `dokter` INT NOT NULL,
  `jns_byr` ENUM("BPJS", "UMUM") NULL,
  `ket` TEXT NULL,
  `jumlah` VARCHAR(45) NULL,
  `biaya` VARCHAR(45) NULL,
  PRIMARY KEY (`idkasir_rj`),
  INDEX `fk_kasir_rj_pasien1_idx` (`no_rm` ASC) VISIBLE,
  INDEX `fk_kasir_rj_dokter1_idx` (`dokter` ASC) VISIBLE,
  CONSTRAINT `fk_kasir_rj_pasien1`
    FOREIGN KEY (`no_rm`)
    REFERENCES `rsdea`.`pasien` (`no_rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kasir_rj_dokter1`
    FOREIGN KEY (`dokter`)
    REFERENCES `rsdea`.`dokter` (`kd_dr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`form_igd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`form_igd` (
  `no_rm` VARCHAR(23) NOT NULL,
  `tgl` DATE NULL,
  `jam` TIME NULL,
  `cr_msk` VARCHAR(45) NULL,
  `tarif` DOUBLE NULL,
  INDEX `fk_form_igd_pasien1_idx` (`no_rm` ASC) VISIBLE,
  CONSTRAINT `fk_form_igd_pasien1`
    FOREIGN KEY (`no_rm`)
    REFERENCES `rsdea`.`pasien` (`no_rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`pelayanan_igd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`pelayanan_igd` (
  `pasien_no_rm` VARCHAR(23) NOT NULL,
  `dokter` VARCHAR(45) NULL,
  `kondisi_masuk` VARCHAR(45) NULL,
  `darurat` VARCHAR(45) NULL,
  `kegiatan` VARCHAR(45) NULL,
  `history pasien` VARCHAR(45) NULL,
  INDEX `fk_pelayanan_igd_pasien1_idx` (`pasien_no_rm` ASC) VISIBLE,
  CONSTRAINT `fk_pelayanan_igd_pasien1`
    FOREIGN KEY (`pasien_no_rm`)
    REFERENCES `rsdea`.`pasien` (`no_rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`diagnosa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`diagnosa` (
  `kd_icdX` INT NOT NULL,
  `nm_diagnosa` VARCHAR(45) NULL,
  PRIMARY KEY (`kd_icdX`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`periksa_igd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`periksa_igd` (
  `kd_priksa` INT NOT NULL,
  `standar` VARCHAR(45) NULL,
  `hasil` VARCHAR(45) NULL,
  `satuan` VARCHAR(45) NULL,
  `kd_dr` INT NOT NULL,
  `ket` TEXT NULL,
  `tgl` DATE NULL,
  `waktu` TIME NULL,
  `diagnosa_kd_icdX` INT NOT NULL,
  INDEX `fk_periksa_igd_periksa1_idx` (`kd_priksa` ASC) VISIBLE,
  INDEX `fk_periksa_igd_dokter1_idx` (`kd_dr` ASC) VISIBLE,
  INDEX `fk_periksa_igd_diagnosa1_idx` (`diagnosa_kd_icdX` ASC) VISIBLE,
  CONSTRAINT `fk_periksa_igd_periksa1`
    FOREIGN KEY (`kd_priksa`)
    REFERENCES `rsdea`.`periksa` (`kd_priksa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periksa_igd_dokter1`
    FOREIGN KEY (`kd_dr`)
    REFERENCES `rsdea`.`dokter` (`kd_dr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periksa_igd_diagnosa1`
    FOREIGN KEY (`diagnosa_kd_icdX`)
    REFERENCES `rsdea`.`diagnosa` (`kd_icdX`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`prosedur_igd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`prosedur_igd` (
  `icd9_kd_icd` INT NOT NULL,
  `prosedur_igdcol` VARCHAR(45) NULL,
  `diagnosa_kd_icdX` INT NOT NULL,
  `ket` TEXT NULL,
  `tgl` DATE NULL,
  `waktu` TIME NULL,
  INDEX `fk_prosedur_igd_icd91_idx` (`icd9_kd_icd` ASC) VISIBLE,
  INDEX `fk_prosedur_igd_diagnosa1_idx` (`diagnosa_kd_icdX` ASC) VISIBLE,
  CONSTRAINT `fk_prosedur_igd_icd91`
    FOREIGN KEY (`icd9_kd_icd`)
    REFERENCES `rsdea`.`icd9` (`kd_icd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prosedur_igd_diagnosa1`
    FOREIGN KEY (`diagnosa_kd_icdX`)
    REFERENCES `rsdea`.`diagnosa` (`kd_icdX`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`tindakan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`tindakan` (
  `kd_tindakan` INT NOT NULL,
  `nm_tindakan` VARCHAR(45) NULL,
  `biaya` DOUBLE NULL,
  PRIMARY KEY (`kd_tindakan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`tindakan_igd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`tindakan_igd` (
  `tindakan_kd_tindakan` INT NOT NULL,
  `pelaksana` INT NOT NULL,
  `tgl` DATE NULL,
  `waktu` TIME NULL,
  INDEX `fk_tindakan_igd_tindakan1_idx` (`tindakan_kd_tindakan` ASC) VISIBLE,
  INDEX `fk_tindakan_igd_pegawai1_idx` (`pelaksana` ASC) VISIBLE,
  CONSTRAINT `fk_tindakan_igd_tindakan1`
    FOREIGN KEY (`tindakan_kd_tindakan`)
    REFERENCES `rsdea`.`tindakan` (`kd_tindakan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tindakan_igd_pegawai1`
    FOREIGN KEY (`pelaksana`)
    REFERENCES `rsdea`.`pegawai` (`no_pgw`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`resep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`resep` (
  `barang` INT NOT NULL,
  `satuan` INT NULL,
  `jumlah` INT NULL,
  `resepcol` VARCHAR(45) NULL,
  PRIMARY KEY (`barang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`bhp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`bhp` (
  `kd_barang` INT NOT NULL,
  `nm_barang` VARCHAR(45) NULL,
  `satuan` INT NULL,
  `harga` DOUBLE NULL,
  PRIMARY KEY (`kd_barang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rsdea`.`bhp_igd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsdea`.`bhp_igd` (
  `barang` INT NOT NULL,
  `satuan` INT NULL,
  `harga` DOUBLE NULL,
  `subtotal` DOUBLE NULL,
  `ket` TEXT NULL)
ENGINE = InnoDB;

USE `sik` ;

-- -----------------------------------------------------
-- Table `sik`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`admin` (
  `usere` TEXT NULL DEFAULT NULL,
  `passworde` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`bidang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`bidang` (
  `nama` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`nama`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`bpjs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`bpjs` (
  `stts` CHAR(5) NOT NULL,
  `biaya` DOUBLE NOT NULL,
  PRIMARY KEY (`stts`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`bpjs_prb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`bpjs_prb` (
  `no_sep` VARCHAR(40) NOT NULL,
  `prb` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`no_sep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`bridging_dukcapil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`bridging_dukcapil` (
  `no_rkm_medis` VARCHAR(15) NOT NULL,
  `no_id` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`no_rkm_medis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`bridging_rujukan_bpjs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`bridging_rujukan_bpjs` (
  `no_sep` VARCHAR(40) NOT NULL,
  `tglRujukan` DATE NULL DEFAULT NULL,
  `ppkDirujuk` VARCHAR(20) NULL DEFAULT NULL,
  `nm_ppkDirujuk` VARCHAR(100) NULL DEFAULT NULL,
  `jnsPelayanan` ENUM('1', '2') NULL DEFAULT NULL,
  `catatan` VARCHAR(200) NULL DEFAULT NULL,
  `diagRujukan` VARCHAR(10) NULL DEFAULT NULL,
  `nama_diagRujukan` VARCHAR(400) NULL DEFAULT NULL,
  `tipeRujukan` ENUM('0. Penuh', '1. Partial', '2. Rujuk Balik') NULL DEFAULT NULL,
  `poliRujukan` VARCHAR(15) NULL DEFAULT NULL,
  `nama_poliRujukan` VARCHAR(50) NULL DEFAULT NULL,
  `no_rujukan` VARCHAR(40) NULL DEFAULT NULL,
  `user` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`no_sep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`cssd_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`cssd_barang` (
  `no_inventaris` VARCHAR(30) NOT NULL,
  `jenis_barang` ENUM('Heacting Set', 'Partus Set', 'Set Bedah') NULL DEFAULT NULL,
  PRIMARY KEY (`no_inventaris`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`dansos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`dansos` (
  `dana` DOUBLE NOT NULL,
  PRIMARY KEY (`dana`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`gambar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`gambar` (
  `inde` INT(11) NOT NULL,
  `bpjs` LONGBLOB NOT NULL,
  PRIMARY KEY (`inde`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`gambar_radiologi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`gambar_radiologi` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `tgl_periksa` DATE NOT NULL,
  `jam` TIME NOT NULL,
  `lokasi_gambar` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`no_rawat`, `tgl_periksa`, `jam`, `lokasi_gambar`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`golongan_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`golongan_barang` (
  `kode` CHAR(4) NOT NULL,
  `nama` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`kode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`golongan_polri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`golongan_polri` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_golongan` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`golongan_tni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`golongan_tni` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_golongan` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`icd9`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`icd9` (
  `kode` VARCHAR(8) NOT NULL,
  `deskripsi_panjang` VARCHAR(250) NULL DEFAULT NULL,
  `deskripsi_pendek` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`kode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`inacbg_coder_nik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`inacbg_coder_nik` (
  `nik` VARCHAR(20) NOT NULL,
  `no_ik` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`nik`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`inacbg_data_terkirim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`inacbg_data_terkirim` (
  `no_sep` VARCHAR(40) NOT NULL,
  `nik` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`no_sep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`inacbg_data_terkirim2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`inacbg_data_terkirim2` (
  `no_sep` VARCHAR(40) NOT NULL,
  `nik` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`no_sep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`inacbg_grouping_stage1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`inacbg_grouping_stage1` (
  `no_sep` VARCHAR(40) NOT NULL,
  `code_cbg` VARCHAR(10) NULL DEFAULT NULL,
  `deskripsi` VARCHAR(200) NULL DEFAULT NULL,
  `tarif` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`no_sep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`inacbg_grouping_stage12`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`inacbg_grouping_stage12` (
  `no_sep` VARCHAR(40) NOT NULL,
  `code_cbg` VARCHAR(10) NULL DEFAULT NULL,
  `deskripsi` VARCHAR(200) NULL DEFAULT NULL,
  `tarif` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`no_sep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`inacbg_klaim_baru`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`inacbg_klaim_baru` (
  `no_sep` VARCHAR(40) NOT NULL DEFAULT '',
  `patient_id` VARCHAR(30) NULL DEFAULT NULL,
  `admission_id` VARCHAR(30) NULL DEFAULT NULL,
  `hospital_admission_id` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`no_sep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`inhealth_jenpel_ruang_rawat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`inhealth_jenpel_ruang_rawat` (
  `kd_kamar` VARCHAR(15) NOT NULL,
  `kode_jenpel_ruang_rawat` VARCHAR(20) NOT NULL,
  `nama_jenpel_ruang_rawat` VARCHAR(100) NULL DEFAULT NULL,
  `tarif` DOUBLE NOT NULL,
  PRIMARY KEY (`kd_kamar`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`insiden_keselamatan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`insiden_keselamatan` (
  `kode_insiden` VARCHAR(5) NOT NULL,
  `nama_insiden` VARCHAR(100) NOT NULL,
  `jenis_insiden` ENUM('KPC', 'KTC', 'KNC', 'KTD', 'Sentinel') NOT NULL,
  `dampak` ENUM('1. Tidak Signifikan', '2. Minor', '3. Moderat', '4. Mayor', '5. Katastropik') NOT NULL,
  PRIMARY KEY (`kode_insiden`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`ipsrsjenisbarang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`ipsrsjenisbarang` (
  `kd_jenis` CHAR(5) NOT NULL,
  `nm_jenis` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`kd_jenis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`jabatan_polri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`jabatan_polri` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_jabatan` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`jabatan_tni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`jabatan_tni` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_jabatan` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`jadwal_tambahan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`jadwal_tambahan` (
  `id` INT(11) NOT NULL,
  `tahun` YEAR(4) NOT NULL,
  `bulan` ENUM('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12') NOT NULL,
  `h1` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h2` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h3` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h4` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h5` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h6` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h7` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h8` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h9` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h10` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h11` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h12` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h13` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h14` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h15` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h16` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h17` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h18` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h19` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h20` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h21` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h22` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h23` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h24` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h25` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h26` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h27` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h28` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h29` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h30` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  `h31` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10', '') NOT NULL,
  PRIMARY KEY (`id`, `tahun`, `bulan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`jam_masuk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`jam_masuk` (
  `shift` ENUM('Pagi', 'Pagi2', 'Pagi3', 'Pagi4', 'Pagi5', 'Pagi6', 'Pagi7', 'Pagi8', 'Pagi9', 'Pagi10', 'Siang', 'Siang2', 'Siang3', 'Siang4', 'Siang5', 'Siang6', 'Siang7', 'Siang8', 'Siang9', 'Siang10', 'Malam', 'Malam2', 'Malam3', 'Malam4', 'Malam5', 'Malam6', 'Malam7', 'Malam8', 'Malam9', 'Malam10', 'Midle Pagi1', 'Midle Pagi2', 'Midle Pagi3', 'Midle Pagi4', 'Midle Pagi5', 'Midle Pagi6', 'Midle Pagi7', 'Midle Pagi8', 'Midle Pagi9', 'Midle Pagi10', 'Midle Siang1', 'Midle Siang2', 'Midle Siang3', 'Midle Siang4', 'Midle Siang5', 'Midle Siang6', 'Midle Siang7', 'Midle Siang8', 'Midle Siang9', 'Midle Siang10', 'Midle Malam1', 'Midle Malam2', 'Midle Malam3', 'Midle Malam4', 'Midle Malam5', 'Midle Malam6', 'Midle Malam7', 'Midle Malam8', 'Midle Malam9', 'Midle Malam10') NOT NULL,
  `jam_masuk` TIME NOT NULL,
  `jam_pulang` TIME NOT NULL,
  PRIMARY KEY (`shift`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`kategori_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`kategori_barang` (
  `kode` CHAR(4) NOT NULL,
  `nama` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`kode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`kesling_limbah_b3medis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`kesling_limbah_b3medis` (
  `nip` VARCHAR(20) NOT NULL,
  `tanggal` DATETIME NOT NULL,
  `jmllimbah` DOUBLE NULL DEFAULT NULL,
  `tujuan_penyerahan` VARCHAR(50) NULL DEFAULT NULL,
  `bukti_dokumen` VARCHAR(20) NULL DEFAULT NULL,
  `sisa_di_tps` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`nip`, `tanggal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`kesling_limbah_domestik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`kesling_limbah_domestik` (
  `nip` VARCHAR(20) NOT NULL,
  `tanggal` DATETIME NOT NULL,
  `jumlahlimbah` DOUBLE NULL DEFAULT NULL,
  `tanggalangkut` DATETIME NULL DEFAULT NULL,
  `keterangan` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`nip`, `tanggal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`kesling_mutu_air_limbah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`kesling_mutu_air_limbah` (
  `nip` VARCHAR(20) NOT NULL,
  `tanggal` DATETIME NOT NULL,
  `meteran` DOUBLE NULL DEFAULT NULL,
  `jumlahharian` DOUBLE NULL DEFAULT NULL,
  `ph` DOUBLE NULL DEFAULT NULL,
  `suhu` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`nip`, `tanggal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`kesling_pemakaian_air_pdam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`kesling_pemakaian_air_pdam` (
  `nip` VARCHAR(20) NOT NULL,
  `tanggal` DATETIME NOT NULL,
  `meteran` DOUBLE NULL DEFAULT NULL,
  `jumlahharian` DOUBLE NULL DEFAULT NULL,
  `keterangan` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`nip`, `tanggal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`kesling_pest_control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`kesling_pest_control` (
  `nip` VARCHAR(20) NOT NULL,
  `tanggal` DATETIME NOT NULL,
  `rincian_kegiatan` TEXT NULL DEFAULT NULL,
  `rekomendasi` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`nip`, `tanggal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`log_dukcapil_aceh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`log_dukcapil_aceh` (
  `no_ktp` VARCHAR(20) NOT NULL,
  `tanggal` DATETIME NOT NULL,
  `user` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`no_ktp`, `tanggal`, `user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`maping_dokter_pcare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`maping_dokter_pcare` (
  `kd_dokter` VARCHAR(20) NOT NULL,
  `kd_dokter_pcare` VARCHAR(20) NULL DEFAULT NULL,
  `nm_dokter_pcare` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`kd_dokter`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`maping_obat_pcare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`maping_obat_pcare` (
  `kode_brng` VARCHAR(15) NOT NULL,
  `kode_brng_pcare` VARCHAR(15) NOT NULL,
  `nama_brng_pcare` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`kode_brng`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`maping_poli_bpjs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`maping_poli_bpjs` (
  `kd_poli_rs` VARCHAR(5) NOT NULL,
  `kd_poli_bpjs` VARCHAR(15) NOT NULL,
  `nm_poli_bpjs` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`kd_poli_rs`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`maping_poliklinik_pcare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`maping_poliklinik_pcare` (
  `kd_poli_rs` CHAR(5) NOT NULL,
  `kd_poli_pcare` CHAR(5) NULL DEFAULT NULL,
  `nm_poli_pcare` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`kd_poli_rs`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`maping_tindakan_pcare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`maping_tindakan_pcare` (
  `kd_jenis_prw` VARCHAR(15) NOT NULL,
  `kd_tindakan_pcare` VARCHAR(15) NULL DEFAULT NULL,
  `nm_tindakan_pcare` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`kd_jenis_prw`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`maping_tindakan_ranap_pcare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`maping_tindakan_ranap_pcare` (
  `kd_jenis_prw` VARCHAR(15) NOT NULL,
  `kd_tindakan_pcare` VARCHAR(15) NULL DEFAULT NULL,
  `nm_tindakan_pcare` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`kd_jenis_prw`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`master_aturan_pakai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`master_aturan_pakai` (
  `aturan` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`aturan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`master_berkas_digital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`master_berkas_digital` (
  `kode` VARCHAR(10) NOT NULL,
  `nama` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`kode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`master_berkas_pegawai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`master_berkas_pegawai` (
  `kode` VARCHAR(10) NOT NULL,
  `kategori` ENUM('Tenaga klinis Dokter Umum', 'Tenaga klinis Dokter Spesialis', 'Tenaga klinis Perawat dan Bidan', 'Tenaga klinis Profesi Lain', 'Tenaga Non Klinis') NOT NULL,
  `nama_berkas` VARCHAR(300) NOT NULL,
  `no_urut` TINYINT(4) NOT NULL,
  PRIMARY KEY (`kode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`metode_racik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`metode_racik` (
  `kd_racik` VARCHAR(3) NOT NULL,
  `nm_racik` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`kd_racik`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`mutasi_berkas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`mutasi_berkas` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `status` ENUM('Sudah Dikirim', 'Sudah Diterima', 'Sudah Kembali', 'Tidak Ada', 'Masuk Ranap') NULL DEFAULT NULL,
  `dikirim` DATETIME NULL DEFAULT NULL,
  `diterima` DATETIME NULL DEFAULT NULL,
  `kembali` DATETIME NULL DEFAULT NULL,
  `tidakada` DATETIME NULL DEFAULT NULL,
  `ranap` DATETIME NOT NULL,
  PRIMARY KEY (`no_rawat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pangkat_polri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pangkat_polri` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_pangkat` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pangkat_tni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pangkat_tni` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_pangkat` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`parkir_jenis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`parkir_jenis` (
  `kd_parkir` CHAR(5) NOT NULL,
  `jns_parkir` VARCHAR(50) NOT NULL,
  `biaya` DOUBLE NOT NULL,
  `jenis` ENUM('Harian', 'Jam') NOT NULL,
  PRIMARY KEY (`kd_parkir`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pasien_mati`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pasien_mati` (
  `tanggal` DATE NULL DEFAULT NULL,
  `jam` TIME NULL DEFAULT NULL,
  `no_rkm_medis` VARCHAR(15) NOT NULL DEFAULT '',
  `keterangan` VARCHAR(100) NULL DEFAULT NULL,
  `temp_meninggal` ENUM('-', 'Rumah Sakit', 'Puskesmas', 'Rumah Bersalin', 'Rumah Tempat Tinggal', 'Lain-lain (Termasuk Doa)', 'Tidak tahu') NULL DEFAULT NULL,
  `icd1` VARCHAR(20) NULL DEFAULT NULL,
  `icd2` VARCHAR(20) NULL DEFAULT NULL,
  `icd3` VARCHAR(20) NULL DEFAULT NULL,
  `icd4` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`no_rkm_medis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pcare_kegiatan_kelompok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pcare_kegiatan_kelompok` (
  `eduId` VARCHAR(15) NOT NULL,
  `clubId` VARCHAR(5) NULL DEFAULT NULL,
  `namaClub` VARCHAR(100) NOT NULL,
  `tglPelayanan` DATE NULL DEFAULT NULL,
  `nmKegiatan` VARCHAR(30) NULL DEFAULT NULL,
  `nmKelompok` VARCHAR(30) NULL DEFAULT NULL,
  `materi` VARCHAR(100) NULL DEFAULT NULL,
  `pembicara` VARCHAR(50) NULL DEFAULT NULL,
  `lokasi` VARCHAR(50) NULL DEFAULT NULL,
  `keterangan` VARCHAR(100) NULL DEFAULT NULL,
  `biaya` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`eduId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pcare_kunjungan_umum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pcare_kunjungan_umum` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `noKunjungan` VARCHAR(40) NULL DEFAULT NULL,
  `tglDaftar` DATE NULL DEFAULT NULL,
  `no_rkm_medis` VARCHAR(15) NULL DEFAULT NULL,
  `nm_pasien` VARCHAR(40) NULL DEFAULT NULL,
  `noKartu` VARCHAR(25) NULL DEFAULT NULL,
  `kdPoli` CHAR(5) NULL DEFAULT NULL,
  `nmPoli` VARCHAR(50) NULL DEFAULT NULL,
  `keluhan` VARCHAR(400) NULL DEFAULT NULL,
  `kdSadar` VARCHAR(5) NULL DEFAULT NULL,
  `nmSadar` VARCHAR(50) NULL DEFAULT NULL,
  `sistole` VARCHAR(3) NULL DEFAULT NULL,
  `diastole` VARCHAR(3) NULL DEFAULT NULL,
  `beratBadan` VARCHAR(5) NULL DEFAULT NULL,
  `tinggiBadan` VARCHAR(5) NULL DEFAULT NULL,
  `respRate` VARCHAR(3) NULL DEFAULT NULL,
  `heartRate` VARCHAR(3) NULL DEFAULT NULL,
  `terapi` VARCHAR(400) NULL DEFAULT NULL,
  `kdStatusPulang` VARCHAR(5) NULL DEFAULT NULL,
  `nmStatusPulang` VARCHAR(50) NULL DEFAULT NULL,
  `tglPulang` DATE NULL DEFAULT NULL,
  `kdDokter` VARCHAR(20) NULL DEFAULT NULL,
  `nmDokter` VARCHAR(50) NULL DEFAULT NULL,
  `kdDiag1` VARCHAR(10) NULL DEFAULT NULL,
  `nmDiag1` VARCHAR(400) NULL DEFAULT NULL,
  `kdDiag2` VARCHAR(10) NULL DEFAULT NULL,
  `nmDiag2` VARCHAR(400) NULL DEFAULT NULL,
  `kdDiag3` VARCHAR(10) NULL DEFAULT NULL,
  `nmDiag3` VARCHAR(400) NULL DEFAULT NULL,
  PRIMARY KEY (`no_rawat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pcare_pendaftaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pcare_pendaftaran` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `tglDaftar` DATE NOT NULL,
  `no_rkm_medis` VARCHAR(15) NOT NULL,
  `nm_pasien` VARCHAR(40) NOT NULL,
  `kdProviderPeserta` VARCHAR(15) NOT NULL,
  `noKartu` VARCHAR(25) NOT NULL,
  `kdPoli` VARCHAR(5) NOT NULL,
  `nmPoli` VARCHAR(50) NOT NULL,
  `keluhan` VARCHAR(400) NOT NULL,
  `kunjSakit` ENUM('Kunjungan Sakit', 'Kunjungan Sehat') NOT NULL,
  `sistole` VARCHAR(3) NOT NULL,
  `diastole` VARCHAR(3) NOT NULL,
  `beratBadan` VARCHAR(5) NOT NULL,
  `tinggiBadan` VARCHAR(5) NOT NULL,
  `respRate` VARCHAR(3) NOT NULL,
  `heartRate` VARCHAR(3) NOT NULL,
  `rujukBalik` VARCHAR(3) NOT NULL,
  `kdTkp` ENUM('10 Rawat Jalan', '20 Rawat Inap', '50 Promotif Preventif') NOT NULL,
  `noUrut` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`no_rawat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pembagian_akte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pembagian_akte` (
  `id` INT(11) NOT NULL,
  `persen` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pembagian_resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pembagian_resume` (
  `id` INT(11) NOT NULL,
  `persen` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pembagian_tuslah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pembagian_tuslah` (
  `id` INT(11) NOT NULL,
  `persen` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pembagian_warung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pembagian_warung` (
  `id` INT(11) NOT NULL,
  `persen` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pemeriksaan_ginekologi_ralan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pemeriksaan_ginekologi_ralan` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `tgl_perawatan` DATE NOT NULL,
  `jam_rawat` TIME NOT NULL,
  `inspeksi` VARCHAR(50) NULL DEFAULT NULL,
  `inspeksi_vulva` VARCHAR(50) NULL DEFAULT NULL,
  `inspekulo_gine` VARCHAR(50) NULL DEFAULT NULL,
  `fluxus_gine` ENUM('+', '-') NULL DEFAULT NULL,
  `fluor_gine` ENUM('+', '-') NULL DEFAULT NULL,
  `vulva_inspekulo` VARCHAR(50) NOT NULL,
  `portio_inspekulo` VARCHAR(50) NULL DEFAULT NULL,
  `sondage` VARCHAR(50) NULL DEFAULT NULL,
  `portio_dalam` VARCHAR(50) NULL DEFAULT NULL,
  `bentuk` VARCHAR(50) NULL DEFAULT NULL,
  `cavum_uteri` VARCHAR(50) NULL DEFAULT NULL,
  `mobilitas` ENUM('+', '-') NULL DEFAULT NULL,
  `ukuran` VARCHAR(50) NULL DEFAULT NULL,
  `nyeri_tekan` ENUM('+', '-') NULL DEFAULT NULL,
  `adnexa_kanan` VARCHAR(50) NULL DEFAULT NULL,
  `adnexa_kiri` VARCHAR(50) NOT NULL,
  `cavum_douglas` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`no_rawat`, `tgl_perawatan`, `jam_rawat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pemeriksaan_ginekologi_ranap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pemeriksaan_ginekologi_ranap` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `tgl_perawatan` DATE NOT NULL,
  `jam_rawat` TIME NOT NULL,
  `inspeksi` VARCHAR(50) NULL DEFAULT NULL,
  `inspeksi_vulva` VARCHAR(50) NULL DEFAULT NULL,
  `inspekulo_gine` VARCHAR(50) NULL DEFAULT NULL,
  `fluxus_gine` ENUM('+', '-') NULL DEFAULT NULL,
  `fluor_gine` ENUM('+', '-') NULL DEFAULT NULL,
  `vulva_inspekulo` VARCHAR(50) NOT NULL,
  `portio_inspekulo` VARCHAR(50) NULL DEFAULT NULL,
  `sondage` VARCHAR(50) NULL DEFAULT NULL,
  `portio_dalam` VARCHAR(50) NULL DEFAULT NULL,
  `bentuk` VARCHAR(50) NULL DEFAULT NULL,
  `cavum_uteri` VARCHAR(50) NULL DEFAULT NULL,
  `mobilitas` ENUM('+', '-') NULL DEFAULT NULL,
  `ukuran` VARCHAR(50) NULL DEFAULT NULL,
  `nyeri_tekan` ENUM('+', '-') NULL DEFAULT NULL,
  `adnexa_kanan` VARCHAR(50) NULL DEFAULT NULL,
  `adnexa_kiri` VARCHAR(50) NOT NULL,
  `cavum_douglas` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`no_rawat`, `tgl_perawatan`, `jam_rawat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pemeriksaan_obstetri_ralan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pemeriksaan_obstetri_ralan` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `tgl_perawatan` DATE NOT NULL,
  `jam_rawat` TIME NOT NULL,
  `tinggi_uteri` VARCHAR(5) NULL DEFAULT NULL,
  `janin` ENUM('Tunggal', 'Gemelli', '-') NULL DEFAULT NULL,
  `letak` VARCHAR(5) NULL DEFAULT NULL,
  `panggul` ENUM('-', '5/5', '4/5', '3/5', '2/5', '1/5') NULL DEFAULT NULL,
  `denyut` VARCHAR(5) NULL DEFAULT NULL,
  `kontraksi` ENUM('+', '-') NULL DEFAULT NULL,
  `kualitas_mnt` VARCHAR(5) NULL DEFAULT NULL,
  `kualitas_dtk` VARCHAR(5) NULL DEFAULT NULL,
  `fluksus` ENUM('+', '-') NULL DEFAULT NULL,
  `albus` ENUM('+', '-') NULL DEFAULT NULL,
  `vulva` VARCHAR(50) NULL DEFAULT NULL,
  `portio` VARCHAR(50) NULL DEFAULT NULL,
  `dalam` ENUM('Kenyal', 'Lunak') NULL DEFAULT NULL,
  `tebal` VARCHAR(5) NULL DEFAULT NULL,
  `arah` ENUM('depan', 'axial', 'belakang') NULL DEFAULT NULL,
  `pembukaan` VARCHAR(50) NULL DEFAULT NULL,
  `penurunan` VARCHAR(50) NULL DEFAULT NULL,
  `denominator` VARCHAR(50) NOT NULL,
  `ketuban` ENUM('-', '+') NULL DEFAULT NULL,
  `feto` ENUM('Normal', 'Susp.CPD-FPD', 'CPD-FPD') NULL DEFAULT NULL,
  PRIMARY KEY (`no_rawat`, `tgl_perawatan`, `jam_rawat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pemeriksaan_obstetri_ranap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pemeriksaan_obstetri_ranap` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `tgl_perawatan` DATE NOT NULL,
  `jam_rawat` TIME NOT NULL,
  `tinggi_uteri` VARCHAR(5) NULL DEFAULT NULL,
  `janin` ENUM('Tunggal', 'Gemelli', '-') NULL DEFAULT NULL,
  `letak` VARCHAR(5) NULL DEFAULT NULL,
  `panggul` ENUM('-', '5/5', '4/5', '3/5', '2/5', '1/5') NULL DEFAULT NULL,
  `denyut` VARCHAR(5) NULL DEFAULT NULL,
  `kontraksi` ENUM('+', '-') NULL DEFAULT NULL,
  `kualitas_mnt` VARCHAR(5) NULL DEFAULT NULL,
  `kualitas_dtk` VARCHAR(5) NULL DEFAULT NULL,
  `fluksus` ENUM('+', '-') NULL DEFAULT NULL,
  `albus` ENUM('+', '-') NULL DEFAULT NULL,
  `vulva` VARCHAR(50) NULL DEFAULT NULL,
  `portio` VARCHAR(50) NULL DEFAULT NULL,
  `dalam` ENUM('Kenyal', 'Lunak') NULL DEFAULT NULL,
  `tebal` VARCHAR(5) NULL DEFAULT NULL,
  `arah` ENUM('depan', 'axial', 'belakang') NULL DEFAULT NULL,
  `pembukaan` VARCHAR(50) NULL DEFAULT NULL,
  `penurunan` VARCHAR(50) NULL DEFAULT NULL,
  `denominator` VARCHAR(50) NOT NULL,
  `ketuban` ENUM('-', '+') NULL DEFAULT NULL,
  `feto` ENUM('Normal', 'Susp.CPD-FPD', 'CPD-FPD') NULL DEFAULT NULL,
  PRIMARY KEY (`no_rawat`, `tgl_perawatan`, `jam_rawat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`peminjaman_koperasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`peminjaman_koperasi` (
  `id` INT(11) NOT NULL,
  `tanggal` DATE NOT NULL,
  `pinjaman` DOUBLE NOT NULL,
  `banyak_angsur` INT(11) NOT NULL,
  `pokok` DOUBLE NOT NULL,
  `jasa` DOUBLE NOT NULL,
  `status` ENUM('Lunas', 'Belum Lunas') NOT NULL,
  PRIMARY KEY (`id`, `tanggal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pendidikan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pendidikan` (
  `tingkat` VARCHAR(80) NOT NULL,
  `indek` TINYINT(4) NOT NULL,
  `gapok1` DOUBLE NOT NULL,
  `kenaikan` DOUBLE NOT NULL,
  `maksimal` INT(11) NOT NULL,
  PRIMARY KEY (`tingkat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pengaduan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pengaduan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL,
  `username` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `message` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`pengurangan_biaya`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`pengurangan_biaya` (
  `no_rawat` VARCHAR(17) NOT NULL DEFAULT '',
  `nama_pengurangan` VARCHAR(60) NOT NULL,
  `besar_pengurangan` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`no_rawat`, `nama_pengurangan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`penjab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`penjab` (
  `kd_pj` CHAR(3) NOT NULL,
  `png_jawab` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`kd_pj`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`penyakit_pd3i`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`penyakit_pd3i` (
  `kd_penyakit` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`kd_penyakit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`permintaan_registrasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`permintaan_registrasi` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `biaya` DOUBLE NOT NULL,
  PRIMARY KEY (`no_rawat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perpustakaan_anggota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perpustakaan_anggota` (
  `no_anggota` VARCHAR(10) NOT NULL,
  `nama_anggota` VARCHAR(40) NULL DEFAULT NULL,
  `tmp_lahir` VARCHAR(20) NULL DEFAULT NULL,
  `tgl_lahir` DATE NULL DEFAULT NULL,
  `j_kel` ENUM('L', 'P') NULL DEFAULT NULL,
  `alamat` VARCHAR(70) NULL DEFAULT NULL,
  `no_telp` VARCHAR(13) NULL DEFAULT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  `tgl_gabung` DATE NULL DEFAULT NULL,
  `masa_berlaku` DATE NULL DEFAULT NULL,
  `jenis_anggota` ENUM('Pasien', 'Pegawai', 'Umum') NOT NULL,
  `nomer_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`no_anggota`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perpustakaan_denda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perpustakaan_denda` (
  `kode_denda` CHAR(5) NOT NULL,
  `jenis_denda` VARCHAR(40) NULL DEFAULT NULL,
  `besar_denda` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`kode_denda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perpustakaan_jenis_buku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perpustakaan_jenis_buku` (
  `id_jenis` CHAR(5) NOT NULL,
  `nama_jenis` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id_jenis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perpustakaan_kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perpustakaan_kategori` (
  `id_kategori` CHAR(5) NOT NULL,
  `nama_kategori` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id_kategori`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perpustakaan_penerbit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perpustakaan_penerbit` (
  `kode_penerbit` VARCHAR(10) NOT NULL,
  `nama_penerbit` VARCHAR(40) NULL DEFAULT NULL,
  `alamat_penerbit` VARCHAR(70) NULL DEFAULT NULL,
  `no_telp` VARCHAR(13) NULL DEFAULT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  `website_penerbit` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`kode_penerbit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perpustakaan_pengarang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perpustakaan_pengarang` (
  `kode_pengarang` VARCHAR(7) NOT NULL,
  `nama_pengarang` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`kode_pengarang`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perpustakaan_ruang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perpustakaan_ruang` (
  `kd_ruang` CHAR(5) NOT NULL DEFAULT '',
  `nm_ruang` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`kd_ruang`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perpustakaan_set_peminjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perpustakaan_set_peminjaman` (
  `max_pinjam` INT(11) NULL DEFAULT NULL,
  `lama_pinjam` INT(11) NULL DEFAULT NULL,
  `denda_perhari` DOUBLE NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`perusahaan_pasien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`perusahaan_pasien` (
  `kode_perusahaan` VARCHAR(8) NOT NULL,
  `nama_perusahaan` VARCHAR(70) NULL DEFAULT NULL,
  `alamat` VARCHAR(100) NULL DEFAULT NULL,
  `kota` VARCHAR(40) NULL DEFAULT NULL,
  `no_telp` VARCHAR(27) NULL DEFAULT NULL,
  PRIMARY KEY (`kode_perusahaan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`riwayat_naik_gaji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`riwayat_naik_gaji` (
  `id` INT(11) NOT NULL,
  `pangkatjabatan` VARCHAR(50) NOT NULL,
  `gapok` DOUBLE NOT NULL,
  `tmt_berkala` DATE NOT NULL,
  `tmt_berkala_yad` DATE NOT NULL,
  `no_sk` VARCHAR(25) NOT NULL,
  `tgl_sk` DATE NOT NULL,
  `masa_kerja` INT(11) NOT NULL,
  `bulan_kerja` INT(11) NOT NULL,
  `berkas` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`, `pangkatjabatan`, `gapok`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`riwayat_pendidikan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`riwayat_pendidikan` (
  `id` INT(11) NOT NULL,
  `pendidikan` ENUM('SD', 'SMP', 'SMA', 'SMK', 'D I', 'D II', 'D III', 'D IV', 'S1', 'S2', 'S3', 'Post Doctor') NOT NULL,
  `sekolah` VARCHAR(50) NOT NULL,
  `jurusan` VARCHAR(40) NOT NULL,
  `thn_lulus` YEAR(4) NOT NULL,
  `kepala` VARCHAR(50) NOT NULL,
  `pendanaan` ENUM('Biaya Sendiri', 'Biaya Instansi Sendiri', 'Lembaga Swasta Kerjasama', 'Lembaga Swasta Kompetisi', 'Lembaga Pemerintah Kerjasama', 'Lembaga Pemerintah Kompetisi', 'Lembaga Internasional') NOT NULL,
  `keterangan` VARCHAR(50) NOT NULL,
  `status` VARCHAR(40) NOT NULL,
  `berkas` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`, `pendidikan`, `sekolah`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`riwayat_penelitian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`riwayat_penelitian` (
  `id` INT(11) NOT NULL,
  `jenis_penelitian` VARCHAR(30) NOT NULL,
  `peranan` VARCHAR(30) NOT NULL,
  `judul_penelitian` VARCHAR(60) NOT NULL,
  `judul_jurnal` VARCHAR(60) NOT NULL,
  `tahun` YEAR(4) NOT NULL,
  `biaya_penelitian` DOUBLE NULL DEFAULT NULL,
  `asal_dana` VARCHAR(30) NOT NULL,
  `berkas` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`, `judul_penelitian`, `tahun`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`riwayat_penghargaan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`riwayat_penghargaan` (
  `id` INT(11) NOT NULL,
  `jenis` VARCHAR(30) NOT NULL,
  `nama_penghargaan` VARCHAR(60) NOT NULL,
  `tanggal` DATE NOT NULL,
  `instansi` VARCHAR(40) NOT NULL,
  `pejabat_pemberi` VARCHAR(40) NOT NULL,
  `berkas` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `nama_penghargaan`, `tanggal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`runtext`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`runtext` (
  `teks` TEXT NOT NULL,
  `aktifkan` ENUM('Yes', 'No') NOT NULL,
  `gambar` LONGBLOB NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`runtextapotek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`runtextapotek` (
  `teks` TEXT NOT NULL,
  `aktifkan` ENUM('Yes', 'No') NOT NULL,
  `gambar` LONGBLOB NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`saran_kesan_lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`saran_kesan_lab` (
  `no_rawat` VARCHAR(17) NOT NULL,
  `tgl_periksa` DATE NOT NULL,
  `jam` TIME NOT NULL,
  `saran` VARCHAR(700) NULL DEFAULT NULL,
  `kesan` VARCHAR(700) NULL DEFAULT NULL,
  PRIMARY KEY (`no_rawat`, `tgl_periksa`, `jam`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sik`.`satuan_polri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sik`.`satuan_polri` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_satuan` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
